const PAGE_ID = {
    WELCOME_PAGE: 0,
    HOME_PAGE: 1,
    REGISTRATION_PAGE: 2,
    BOOK_PAGE: 3,
    VOICE_PAGE: 4,
    ACCOUNT_PAGE: 5,
    LIBRARY_PAGE: 6,
    SHELF_PAGE: 7,
    BOOK_INFORMATION_PAGE: 8,
    CHANGE_PASSWORD_PAGE: 9,
    AUDIO_FOLDER_PAGE: 10
};

export default PAGE_ID;